/**
 * Backfill existing late-unapply card chat messages onto the new format.
 *
 * Cards used to post as `type: "log"` with `author_id` set to the carded
 * player, so the chat rendered Poteau's words under that player's name and
 * avatar. They now post as `poteau_team_message`, and the body carries the
 * player's name exactly once instead of three times.
 *
 * This rewrites the messages already in the chat so history matches. The
 * wording is regenerated by calling the SAME cardTexts() the Cloud Function
 * uses -- not a copy -- so this script cannot drift from production copy.
 *
 * The player's name and gender are re-read from their user doc rather than
 * parsed out of the old French sentence: `author_name` holds the first name
 * that was current when the card was issued, but gender was never stored on
 * the message.
 *
 * Idempotent: a message already on the new type and wording is skipped.
 *
 *   node backfill_card_messages.js --dry     preview, writes nothing
 *   node backfill_card_messages.js           apply
 */
const admin = require('firebase-admin');
const sa = require('./krank-club-firebase-adminsdk-bl4zy-d8facdf022.json');

const {
    cardTexts,
} = require('../cloud-functions/functions/shared/lateUnapplyCards.js');

admin.initializeApp({ credential: admin.credential.cert(sa), projectId: 'krank-club' });
const db = admin.firestore();

const DRY = process.argv.includes('--dry');
const TRIGGERS = ['late_unapply_yellow_card', 'late_unapply_red_card'];

(async () => {
    let scanned = 0;
    let updated = 0;
    let skipped = 0;
    let failed = 0;

    for (const trigger of TRIGGERS) {
        const snap = await db.collection('messages').where('trigger', '==', trigger).get();
        const isRed = trigger === 'late_unapply_red_card';
        console.log(`\n=== ${trigger}: ${snap.size} message(s) ===`);

        for (const doc of snap.docs) {
            scanned++;
            const data = doc.data();

            // The name on the message is what the player was called when the
            // card was issued. Prefer it over today's profile: rewriting
            // history to a name they since changed would be a different edit.
            let firstName = data.author_name || null;
            let gender = null;

            const authorRef = data.author_id;
            if (authorRef) {
                try {
                    const userSnap = await authorRef.get();
                    if (userSnap.exists) {
                        const u = userSnap.data();
                        gender = u.gender || null;
                        if (!firstName) firstName = u.first_name || u.display_name || null;
                    }
                } catch (err) {
                    console.warn(`  ${doc.id}: could not read author (${err.message}), defaulting gender`);
                }
            }

            const texts = cardTexts(isRed, firstName, gender);
            const alreadyDone = data.type === 'poteau_team_message' && data.text === texts.text;
            if (alreadyDone) {
                skipped++;
                console.log(`  = ${doc.id} already migrated, skipping`);
                continue;
            }

            console.log(`  ${DRY ? '~' : '>'} ${doc.id} (${firstName || 'unknown'}, gender=${gender || 'unset'})`);
            console.log(`      old: ${data.text}`);
            console.log(`      new: ${texts.text}`);

            if (DRY) continue;

            try {
                // type and the four language fields only. author_id stays on
                // the carded player -- it records who the card is about, and
                // the client no longer renders it for this type.
                await doc.ref.update({ type: 'poteau_team_message', ...texts });
                updated++;
            } catch (err) {
                failed++;
                console.error(`      FAILED: ${err.message}`);
            }
        }
    }

    console.log(`\n${DRY ? 'DRY RUN' : 'APPLIED'}: scanned ${scanned}, updated ${updated}, skipped ${skipped}, failed ${failed}`);
    process.exit(failed > 0 ? 1 : 0);
})();
