#!/bin/zsh
# Vendor the Poteau Daily into the Cloud Functions deploy.
#
# WHY A COPY. `firebase deploy` uploads ONLY the functions directory. The logic
# lives in the scripts repo — a sibling, and a separate git remote — so a
# relative require would resolve on this Mac and fail in the deployed function
# with MODULE_NOT_FOUND. A path dependency has the same problem: npm would need
# the sibling directory present at install time inside Google's builder.
#
# So daily_signals.js is copied to cloud-functions/functions/vendor/ before
# deploying. The copy is generated, never edited: edit
# scripts/daily_signals.js and re-run this.
#
# RUN THIS BEFORE DEPLOYING dailySignals, or the cloud keeps running the
# previous version while the Mac runs the new one — the exact drift the
# shared-host design exists to prevent.
#
#   ./scripts/sync_daily_signals.sh
set -e

SRC_DIR="/Users/tmgnr/poteau-workspace/scripts"
DEST_DIR="/Users/tmgnr/poteau-workspace/cloud-functions/functions/vendor"

mkdir -p "$DEST_DIR"

cp "$SRC_DIR/daily_signals.js" "$DEST_DIR/daily_signals.js"
echo "vendored daily_signals.js"

# The Mac host is NOT vendored on purpose: it shells out to the `claude` CLI and
# curl, neither of which exists in a Cloud Function. The cloud supplies its own
# host (gen2/dailySignalsHost.js) via setHost(). But daily_signals.js lazily
# requires the Mac host as its default, so that require must resolve — stub it
# with a module that throws only if actually used.
cat > "$DEST_DIR/daily_signals_host.js" <<'STUB'
// GENERATED by scripts/sync_daily_signals.sh — do not edit.
//
// The deployed Daily never uses this: gen2/dailySignals.js calls
// setHost(cloudHost) before building. It exists so the lazy default `require`
// in daily_signals.js resolves inside the function bundle.
//
// Every method throws rather than returning empty. A silent stub would produce
// a confident "nothing needs a look today" that nobody could distinguish from a
// real quiet day, which is worse than a crash that posts a failure notice.
const nope = (m) => () => {
  throw new Error(
    `daily_signals_host.${m}() called in the cloud — setHost(cloudHost) was not applied`
  );
};
module.exports = {
  name: "stub",
  askModel: nope("askModel"),
  postSlack: nope("postSlack"),
};
STUB
echo "wrote stub daily_signals_host.js"

echo
echo "now: cd cloud-functions/functions && npx firebase deploy --only functions:dailySignals,functions:runDailySignals"
