#!/bin/zsh
# Vendor the health report into the Cloud Functions deploy.
#
# WHY A COPY. `firebase deploy` uploads ONLY the functions directory. The report
# lives in the scripts repo — a sibling, and a separate git remote — so a
# relative require would resolve on this Mac and fail in the deployed function
# with MODULE_NOT_FOUND. A path dependency has the same problem: npm would need
# the sibling directory present at install time inside Google's builder.
#
# So the report is copied to cloud-functions/functions/vendor/ before deploying.
# The copy is generated, never edited: edit scripts/daily_health_report.js and
# re-run this.
#
# RUN THIS BEFORE DEPLOYING dailyHealthReport, or the cloud keeps running the
# previous version of the report while the Mac runs the new one — the exact
# drift the shared-host design exists to prevent.
#
#   ./scripts/sync_health_report.sh
set -e

SRC_DIR="/Users/tmgnr/poteau-workspace/scripts"
DEST_DIR="/Users/tmgnr/poteau-workspace/cloud-functions/functions/vendor"

mkdir -p "$DEST_DIR"

for f in daily_health_report.js; do
  cp "$SRC_DIR/$f" "$DEST_DIR/$f"
  echo "vendored $f"
done

# The Mac host is NOT vendored on purpose: it shells out to gcloud and git,
# neither of which exists in a Cloud Function. The cloud supplies its own host
# (gen2/healthReportHost.js) via setHost(). But daily_health_report.js requires
# the Mac host at module load to use as its default, so that require must
# resolve — stub it with a module that throws only if actually used.
cat > "$DEST_DIR/health_report_host.js" <<'STUB'
// GENERATED by scripts/sync_health_report.sh — do not edit.
//
// The deployed report never uses this: gen2/dailyHealthReport.js calls
// setHost(cloudHost) before building. It exists so the default `require` in
// daily_health_report.js resolves inside the function bundle.
//
// Every method throws rather than returning empty. A silent empty host would
// produce a report claiming zero errors and zero crons — a confident, wrong
// "all clear", which is worse than a crash that posts a failure notice.
const nope = (m) => () => {
  throw new Error(
    `health_report_host.${m}() called in the cloud — setHost(cloudHost) was not applied`
  );
};
module.exports = {
  name: "stub",
  readLogs: nope("readLogs"),
  listCronJobs: nope("listCronJobs"),
  recentDeploys: nope("recentDeploys"),
  postSlack: nope("postSlack"),
};
STUB
echo "wrote stub health_report_host.js"

echo
echo "now: cd cloud-functions/functions && npx firebase deploy --only functions:dailyHealthReport,functions:runHealthReport"
