/**
 * Reinstate Selrahc (KtiFZn0XboUoofGbUoULf2oaFrC2) after his appeal.
 *
 * WHY
 *
 * Banned 2026-09-03 for publishing five fake games at Camp des Loges used as a
 * recruitment ad for an outside team ("le match n'aura pas lieu" + phone
 * number). He appealed, acknowledged the misuse, and committed to stopping.
 * Tim's call: reinstate.
 *
 * WHAT IS AND IS NOT RESTORED
 *
 * - banned -> false, and the 5 repeaters go back to published. Their weekly
 *   ladder is his genuine recurring game, unrelated to the recruitment stunt.
 * - The 13 non-spam future games (empty descriptions, generated by those
 *   repeaters) are restored to published.
 * - The 5 SPAM games stay canceled. Their description IS the abuse; restoring
 *   them would republish the recruitment ad. He can create a real game instead.
 *
 * Past games were never touched by the ban and are not touched here.
 *
 * DRY BY DEFAULT. Pass --write to apply.
 */
const admin = require("firebase-admin");
const serviceAccount = require("./krank-club-firebase-adminsdk-bl4zy-d8facdf022.json");
if (!admin.apps.length) {
    admin.initializeApp({ credential: admin.credential.cert(serviceAccount), projectId: "krank-club" });
}
const db = admin.firestore();

const WRITE = process.argv.includes("--write");
const UID = "KtiFZn0XboUoofGbUoULf2oaFrC2";
// Kept canceled: the recruitment ad itself.
const SPAM = new Set([
    "4xkwV20fdmgFVomw7BH3", "Z1Wm54oxKKn8l3g7J01u", "oOkdzs8ES8yrd2zj36q4",
    "lUThFC90STjp4IU5hj7J", "JhEKhOdWc0eORJuiI1Rl",
]);

(async () => {
    const userRef = db.collection("users").doc(UID);
    console.log(`banned before: ${(await userRef.get()).get("banned")}`);

    const now = new Date();
    const snap = await db.collection("games").where("organizer", "==", UID).get();
    const toRestore = snap.docs.filter(g => {
        const date = g.get("date");
        return date && date.toDate() > now
            && g.get("status") === "canceled"
            && !SPAM.has(g.id);
    });

    console.log(`\ngames to restore to published: ${toRestore.length}`);
    for (const g of toRestore) {
        console.log(`  ${g.id} ${g.get("date").toDate().toISOString().slice(0, 16)}`);
    }
    console.log(`\nspam games kept canceled: ${SPAM.size}`);

    const reps = await db.collection("repeaters").where("organizer", "==", UID).get();
    const paused = reps.docs.filter(r => r.get("status") === "paused");
    console.log(`repeaters to republish: ${paused.length}`);

    if (!WRITE) {
        console.log("\nDRY RUN — nothing written");
        process.exit(0);
    }

    await userRef.update({ banned: false });
    for (const r of paused) {
        await r.ref.update({
            status: "published",
            paused_reason: admin.firestore.FieldValue.delete(),
            paused_at: admin.firestore.FieldValue.delete(),
        });
    }
    for (const g of toRestore) {
        await g.ref.update({ status: "published" });
    }
    console.log(`\nAPPLIED — banned=false, repeaters republished: ${paused.length}, games restored: ${toRestore.length}`);
    process.exit(0);
})();
