// Import necessary modules
const admin = require('firebase-admin');
const serviceAccount = require('./krank-club-firebase-adminsdk-bl4zy-d8facdf022.json');

// Initialize Firebase
admin.initializeApp({
    credential: admin.credential.cert(serviceAccount),
    projectId: 'krank-club'
});

const db = admin.firestore();

// JSON array with updated league values
const updatedClubs = [
    { "id": "06nqN7sO2j5pB39qBrmI", "league": "🇩🇪" },
    { "id": "07GjHasp5hsLM2SPCHKf", "league": "🇺🇸" },
    { "id": "0BAl0hVaKQwKuPZ0EbJZ", "league": "🇫🇷" },
    { "id": "0LA22eajFBt6qRYTafAo", "league": "🇧🇷" },
    { "id": "0M2NByb7RAgEcio6y98u", "league": "🇬🇧" },
    { "id": "0YpPlcEERhF2rexAv0E6", "league": "🇧🇷" },
    { "id": "0qrWfEseYMUtiuEtjL3M", "league": "🇪🇸" },
    { "id": "0xdYTFQauTrPAnFgkiCy", "league": "🇪🇸" },
    { "id": "1Pws7Ep0uwzYurgThqZD", "league": "🇺🇸" },
    { "id": "1cuxtzsnjXlB0SieO3c8", "league": "🇫🇷" },
    { "id": "1fVOhHAPhnQ48HADNGzI", "league": "🌍" },
    { "id": "1k4cg5leBUyZJ31LrUyS", "league": "🇦🇷" },
    { "id": "2V6VoT6qUEyPSynweP8p", "league": "🇪🇸" },
    { "id": "2jSBXZE4vRdXCw30F3iF", "league": "🇮🇹" },
    { "id": "39KftYAnNNi7Et3hbC8p", "league": "🌍" },
    { "id": "3a8fFB44b03S0B6fWbuL", "league": "🇫🇷" },
    { "id": "41spIwvv9grdKRpVxmW8", "league": "🇬🇧" },
    { "id": "56CIKM51aA59H97SNXlB", "league": "🇺🇸" },
    { "id": "5LBSnRuC75aLPg9kvI5T", "league": "🌍" },
    { "id": "5QCqiEUbetBj7hzKt3og", "league": "🇺🇸" },
    { "id": "5a2YxGZqryfVlXSxCEJr", "league": "🇵🇹" },
    { "id": "5cgiETwjI9KATOAuZAUW", "league": "🇫🇷" },
    { "id": "6EBX5gwrkOrBnZGLxNmd", "league": "🌍" },
    { "id": "6kpbjU0ycArqbJxYVG42", "league": "🇫🇷" },
    { "id": "6lGOZBonpTp1Cu4pr3IN", "league": "🇮🇹" },
    { "id": "73xy5NPo6yPwRStO27IS", "league": "🇫🇷" },
    { "id": "78TXT3AZow0s9pBgNXFi", "league": "🇺🇸" },
    { "id": "7NJTP8Afi4KM7p59IiVi", "league": "🇮🇹" },
    { "id": "7UCckke6dhSuQiI93lSc", "league": "🇮🇹" },
    { "id": "7dyUQSqxSBVRIW4sXy3h", "league": "🇫🇷" },
    { "id": "84MGoqW7MRzRCBmP1E44", "league": "🇫🇷" },
    { "id": "8H2OqoTSsQaZhI3ImWiG", "league": "🇫🇷" },
    { "id": "8Sor4gcDwK3KDbqiluAY", "league": "🇺🇸" },
    { "id": "8oPoCLYeDlx8JzCCwDKO", "league": "🇺🇸" },
    { "id": "93GRpZHRBTHXgIfNddzy", "league": "🇧🇷" },
    { "id": "9PJMP7ZGTASDsZU9QH9j", "league": "🇫🇷" },
    { "id": "9VyVkh9lf8uGrk7tn0Jl", "league": "🇫🇷" },
    { "id": "9Z4KnsjObDOJrPIYQ0lN", "league": "🌍" },
    { "id": "9aFPErKZLJLkEOXawoEy", "league": "🇩🇪" },
    { "id": "9i9SJToWhavk9Ctd4GQv", "league": "🇩🇪" },
    { "id": "9wiTCEan18OjqT9pBzJp", "league": "🇪🇸" },
    { "id": "AJaNmrYXsnkzldWYNBHq", "league": "🇫🇷" },
    { "id": "AKvyVjqGdhk9UhSSGvoJ", "league": "🌍" },
    { "id": "AOQ2J1MJvlj8WpkKcQde", "league": "🇺🇸" },
    { "id": "AOQxcY2EDeujSI4yI6DK", "league": "🇫🇷" },
    { "id": "ASm6UnGea1fxKGCB0iKI", "league": "🇦🇷" },
    { "id": "AzTEFiMqDggWDEfPPqNr", "league": "🇫🇷" },
    { "id": "B4qx4LM2KCHmR9QHvnnu", "league": "🇧🇷" },
    { "id": "BE3VvwO6WqdLAm4jFVeq", "league": "🇩🇪" },
    { "id": "BhsvI2jGk15WIjQZCb3u", "league": "🇺🇸" },
    { "id": "C3Q3SnJ9brCFl9v5VKSR", "league": "🇺🇸" },
    { "id": "C4cKonHveauTCoBJir2K", "league": "🇮🇹" },
    { "id": "CeBmCgoRBCDkKkEAStxv", "league": "🇬🇧" },
    { "id": "CfyzqHkYa9RPTHN6i6xp", "league": "🌍" },
    { "id": "D0ANqnGGlbbibbiTSIss", "league": "🇮🇹" },
    { "id": "DAtHMSziPqxxqnXzZxkV", "league": "🇩🇪" },
    { "id": "DxPHu50rUuH4KmwGho5y", "league": "🇫🇷" },
    { "id": "EXGTFoOqWbCZnbGrXrS4", "league": "🇮🇹" },
    { "id": "ErRnHpRWeKIKCSUANVTl", "league": "🇫🇷" },
    { "id": "FOKySzK4d5VxEl0V8gWI", "league": "🇩🇪" },
    { "id": "Fdl2tA0Lq1BbYjDnNKa7", "league": "🇬🇧" },
    { "id": "Ff0LWyWo65xwISg8nxkK", "league": "🇬🇧" },
    { "id": "FiK0GnCMabrgjfIoHsee", "league": "🇫🇷" },
    { "id": "FkUafUuuXlXNJgSxv8wG", "league": "🇪🇸" },
    { "id": "GFly0fSDoXYpDx3XvGet", "league": "🇧🇷" },
    { "id": "GHL37dDZz2ZsE7hXvqmX", "league": "🇵🇹" },
    { "id": "GJeZCnyQgGvQXS2bHmMJ", "league": "🇺🇸" },
    { "id": "GY5bKkJAlWQPfBeS7JyY", "league": "🇬🇧" },
    { "id": "GvgqkojgKJYDdzLZpRpO", "league": "🇩🇪" },
    { "id": "HFW6KSQg3d3CesaLqVaT", "league": "🇩🇪" },
    { "id": "HXW6QinK4ZsiJOSqpWuM", "league": "🇪🇸" },
    { "id": "HyKrHKAqpLtUaU0jSwGo", "league": "🌍" },
    { "id": "HySd28nfKwLfPT3G1bMS", "league": "🌍" },
    { "id": "I7i2dS02Daa4ezSLJTzs", "league": "🌍" },
    { "id": "IWDsVYn5asRNcsvZbAWi", "league": "🇬🇧" },
    { "id": "In1l4vEDXBXODqOu4Gca", "league": "🌍" },
    { "id": "IodTXAQMaxTiTFQPA7bO", "league": "🇪🇸" },
    { "id": "JJHnGUWc57bAl9v8LkO7", "league": "🇺🇸" },
    { "id": "JTvhXSP2I0YVxqINQ5xw", "league": "🇫🇷" },
    { "id": "JUzpwDRoHpcPiIiTYzI8", "league": "🇩🇪" },
    { "id": "JoKVkIrCUqTYyvBSlSqs", "league": "🇬🇧" },
    { "id": "JsvPNtitrzu4yB6mvZDz", "league": "🇫🇷" },
    { "id": "KA8JqFRS7Yqe4tf4N1Tr", "league": "🇩🇪" },
    { "id": "Kmktae4nomqUbUSQ0uvh", "league": "🇪🇸" },
    { "id": "KmxU3ynnZxZZhddLyksH", "league": "🇬🇧" },
    { "id": "LOQtjD9LHvHDJh6sGADj", "league": "🇮🇹" },
    { "id": "LhwsD4eneeyP44U2d2Y9", "league": "🇬🇧" },
    { "id": "LuVABNv7ID4BM2sj7Tmy", "league": "🇺🇸" },
    { "id": "M3XMpCD1KyFVqYBDa0HY", "league": "🇧🇷" },
    { "id": "MKPPCghcV7FbO90YGvJs", "league": "🇪🇸" },
    { "id": "MSrZMmBVjhGw1b4LOYcx", "league": "🇫🇷" },
    { "id": "MUmjSSDacrDO0xj8csBw", "league": "🇺🇸" },
    { "id": "MbjFqkJYQICXwMt55njB", "league": "🇵🇹" },
    { "id": "MsHbwAkj685cmlWFT2GE", "league": "🇪🇸" },
    { "id": "MzJh4sEerocGLbfWcDhI", "league": "🇪🇸" },
    { "id": "MzSYgkDFQfmhGh8mriiE", "league": "🇫🇷" },
    { "id": "OHurvFppd0pgLTLutbtK", "league": "🇺🇸" },
    { "id": "OMxl07uCtPtEaCukpuGK", "league": "🇺🇸" },
    { "id": "OYbAjC6PAT2OIpN4sGIB", "league": "🇩🇪" },
    { "id": "OeWZkgGqBdRM1sHqcgru", "league": "🌍" },
    { "id": "Ov6GbIk0svUAVkuLIQCS", "league": "🌍" },
    { "id": "PCxtKUyLrlv2TpJ2uKtu", "league": "🇪🇸" },
    { "id": "QIHjwXyxhn07xn0W11FK", "league": "🌍" },
    { "id": "QWKY0RyapN9wpGrhONG5", "league": "🇩🇪" },
    { "id": "Qp9A2ykKQUKyiSIBgkjp", "league": "🇮🇹" },
    { "id": "QqZVkPytqZSvhUsZCgOI", "league": "🇪🇸" },
    { "id": "RHeM7ZfSaMaf126FXFnP", "league": "🇪🇸" },
    { "id": "RVmVcUw1eyWPLWBwHL5h", "league": "🇦🇷" },
    { "id": "SBS2Zl2AJZXednXszf1A", "league": "🇮🇹" },
    { "id": "SOq8SBtFe98Be9UHtMCu", "league": "🇧🇷" },
    { "id": "T2F4EFQHNplWTOXmSJ9R", "league": "🇫🇷" },
    { "id": "TaC1HYlMYZuES2G983Eb", "league": "🇺🇸" },
    { "id": "TmGLxGYs1oDm8HvJID9R", "league": "🇩🇪" },
    { "id": "TqQeLDFuCcz5tInNqgsA", "league": "🇧🇷" },
    { "id": "U3VpIueeLejzshzQmC4O", "league": "🇺🇸" },
    { "id": "UUaSnKz4jRGNkLs9Ng94", "league": "🌍" },
    { "id": "UtDr26Ggh5IPW0IR7b8O", "league": "🇪🇸" },
    { "id": "Uye3539kPFP7C4PyPNud", "league": "🇬🇧" },
    { "id": "V0drmnRXiGSK83bkMWoi", "league": "🇮🇹" },
    { "id": "VEBJe3QJxFzGCCcyOTSx", "league": "🇮🇹" },
    { "id": "VNKmSuqMOY9OEDd2c0pV", "league": "🌍" },
    { "id": "WaLrGJ0Z3UgTiidWKLJy", "league": "🇬🇧" },
    { "id": "X2ytFrgANeqJvFILKBFd", "league": "🇪🇸" },
    { "id": "X6eXqR8WWPWI5Dqy7dMo", "league": "🇬🇧" },
    { "id": "XS2gRiU7PyA2hs3CAHsQ", "league": "🇬🇧" },
    { "id": "Xm8KQCPbh5YJP1uRgr0T", "league": "🌍" },
    { "id": "YB0RJKSuCttOyu70OvOV", "league": "🇦🇷" },
    { "id": "YPhZk0nYwICY8tiJDXPE", "league": "🇪🇸" },
    { "id": "Ymb8eJmh3eSv0DDMJUnx", "league": "🇮🇹" },
    { "id": "YvBlMknESLDlnHq9jgVi", "league": "🇬🇧" },
    { "id": "Z6uAYCjluyg93kTc1hUU", "league": "🇧🇷" },
    { "id": "Z7IPxYxX6YJJjg4P48BM", "league": "🇫🇷" },
    { "id": "ZStMTfMIIvsfhOqcmV99", "league": "🌍" },
    { "id": "a7RvfgzujYWHrRIKxfGo", "league": "🇮🇹" },
    { "id": "aFQJarhJaASuhtg4ZxY0", "league": "🇮🇹" },
    { "id": "aOVNFtDn5ZilPvuXg4wW", "league": "🇧🇷" },
    { "id": "aRTKlyEMsdt5OuGvG0Qp", "league": "🇺🇸" },
    { "id": "ah0k5euHBGbgxv8ZOuQ0", "league": "🇩🇪" },
    { "id": "bMabNbTwm4CNLmX87EFC", "league": "🇮🇹" },
    { "id": "bcoATLagRGhnX9dPiCcd", "league": "🇮🇹" },
    { "id": "bycBJPiQhEl1DJ4r6nVs", "league": "🇺🇸" },
    { "id": "c3KAt0VlQvpLdfMewWhq", "league": "🇬🇧" },
    { "id": "cR0Ku1eN86C2B5HCUGqg", "league": "🇫🇷" },
    { "id": "cW9euV7mQBMubDYezCT9", "league": "🇮🇹" },
    { "id": "cdH1RE4nUi2CB3DrlMVr", "league": "🇫🇷" },
    { "id": "dIFTSB9L04PssnbmEhzV", "league": "🇺🇸" },
    { "id": "dV9JJOQk2I05zYCx1SUF", "league": "🇮🇹" },
    { "id": "dkJyi0A19l2LPmYIX7UN", "league": "🇪🇸" },
    { "id": "fInS6pkOyzYsFGGPnZtJ", "league": "🇮🇹" },
    { "id": "fJn9WPaYpUDvlH2ipVX6", "league": "🇵🇹" },
    { "id": "fUpGjn5rqIR96GUu5Tm3", "league": "🌍" },
    { "id": "fiKIdY0ZCvRwiogDQewl", "league": "🇪🇸" },
    { "id": "fx6YHdRtoSR4kwj6TmmM", "league": "🌍" },
    { "id": "gHUnjxkhCElCzcNt9lQC", "league": "🇫🇷" },
    { "id": "gTNlPU6XZ9r9whHqhRYG", "league": "🇺🇸" },
    { "id": "gwG2Xiwr9bz5QfhYpbKX", "league": "🇺🇸" },
    { "id": "ht5LoTmkQos3xIjVlF5l", "league": "🌍" },
    { "id": "iJlb8uOJcEeU7kgchBo3", "league": "🇬🇧" },
    { "id": "ibYIwHU2tM2cwcwj7LTC", "league": "🇩🇪" },
    { "id": "jOFWM3ON3NPKJir6WtNR", "league": "🇫🇷" },
    { "id": "jeYBdhAPnUJZLLLYV4PP", "league": "🌍" },
    { "id": "jp3COeZMYACu08SL6dac", "league": "🇫🇷" },
    { "id": "kAbRDBh0zbwk6kVQCQ8S", "league": "🇪🇸" },
    { "id": "kHdxmNYDpiYcnF6z5oGr", "league": "🇪🇸" },
    { "id": "kPvBsg53AMLScZ7XfwNK", "league": "🇺🇸" },
    { "id": "kQa3sKfjJQ4JBytbFbsz", "league": "🇩🇪" },
    { "id": "kv4LCELNxvJLVJCPef3e", "league": "🌍" },
    { "id": "lG2asmqUAWlJZyZrZF51", "league": "🇩🇪" },
    { "id": "lMbO7vwGS1xOObuqmIpL", "league": "🇫🇷" },
    { "id": "lxfn73fX6Os5UFkDPwtA", "league": "🌍" },
    { "id": "mfgoykvHLCXiuexwnxcV", "league": "🇪🇸" },
    { "id": "mo9JC2sDBfvqrIdWNXao", "league": "🇬🇧" },
    { "id": "mzDIweoZtwTBLoAnkrOv", "league": "🌍" },
    { "id": "nU38dDrkhpAXoqB0Qdhg", "league": "🇫🇷" },
    { "id": "ncTGAdSK3ZPm2SLCPDGj", "league": "🌍" },
    { "id": "oKfBOrF0GQ69uJcLU8Vg", "league": "🇺🇸" },
    { "id": "poFVCcOfNTR9QvKLrzna", "league": "🇺🇸" },
    { "id": "poKSAAQxxxG0jSTVrEOF", "league": "🇫🇷" },
    { "id": "ppSigilkRlSzp4UupgGc", "league": "🇺🇸" },
    { "id": "q2ld456ppvNkI2JCK5K5", "league": "🇬🇧" },
    { "id": "qC8jV7FT6ZkNRnQIvzdx", "league": "🇫🇷" },
    { "id": "qScmyLy1dTdVOsJACyyR", "league": "🇫🇷" },
    { "id": "qZwNznOCO4XTdjJhgVGw", "league": "🇫🇷" },
    { "id": "qrOGXmrTHynFeHVwcxOv", "league": "🌍" },
    { "id": "qsptJSPEtlFc2F6yYeMB", "league": "🇬🇧" },
    { "id": "rrzIPgdkLbiUdWsTy3Mw", "league": "🇪🇸" },
    { "id": "rvEoMDfMGUiT9HryhFES", "league": "🌍" },
    { "id": "s1pHrd4m7f2NqFfyfYzp", "league": "🇬🇧" },
    { "id": "sD5O1o1gRZYYwPiFu10M", "league": "🌍" },
    { "id": "sEqWR8M6LbNWW5JhNLAf", "league": "🇬🇧" },
    { "id": "sIHAu0X2CNqkGZgJrzjT", "league": "🌍" },
    { "id": "sb4x6kQP1qzjXowtTpjh", "league": "🇧🇷" },
    { "id": "tNxMw7Mcg2bimjB9Sb2U", "league": "🇫🇷" },
    { "id": "tn5uY8I5j7TLsa01uAOr", "league": "🇮🇹" },
    { "id": "uG9AXzmymQyeUTCDQn0e", "league": "🇫🇷" },
    { "id": "uNJt6WQgi705kYtb7Zi0", "league": "🇮🇹" },
    { "id": "uOEfe2rE9Ys4uLeLYP1k", "league": "🇩🇪" },
    { "id": "uU2o2t5FKku6yeMnEMF1", "league": "🇪🇸" },
    { "id": "vmFqpYqjWCwN8NrSmx58", "league": "🇺🇸" },
    { "id": "w7CWcR9BMvwcikhldDv1", "league": "🇮🇹" },
    { "id": "xOD4qSi05DQp2cP1xgH4", "league": "🇫🇷" },
    { "id": "xjxw4dAJdq9KMQhlVmSf", "league": "🇺🇸" },
    { "id": "yIPV3DttFmowWCelC0cU", "league": "🇬🇧" },
    { "id": "yIvh9N8wlv7cl8GpdkyR", "league": "🇫🇷" },
    { "id": "yNLunPHPVmZlYb27Nde5", "league": "🌍" },
    { "id": "yPUjllvH9PKNY1x3rzUy", "league": "🇮🇹" },
    { "id": "ykxUhj0ZSTG8LC4bRt7l", "league": "🇬🇧" },
    { "id": "yywB1xiCuAAVJjn1B680", "league": "🇬🇧" },
    { "id": "zCXqVflUlS9Rh9OcLKzh", "league": "🇩🇪" },
    { "id": "zHGnM1GIumhoj9Qo4bOs", "league": "🌍" },
    { "id": "zVacTjzRKpSmDLKrWSEI", "league": "🌍" }
];

async function updateClubs() {
    const batch = db.batch();

    updatedClubs.forEach(club => {
        const clubRef = db.collection('clubs').doc(club.id);
        batch.update(clubRef, { league: club.league });
    });

    await batch.commit();
    console.log('Clubs successfully updated.');
}

updateClubs().catch(console.error);